In [2]:
import pandas as pd
import numpy as np

In [6]:
nhsn = pd.read_csv("NSSP_Emergency_Department_Visit_Trajectories_by_State_and_Sub_State_Regions-_COVID-19__Flu__RSV__Combined__.csv")

In [7]:
nhsn.head()

,week_end,geography,county,percent_visits_combined,percent_visits_covid,percent_visits_influenza,percent_visits_rsv,percent_visits_smoothed_combined,percent_visits_smoothed_covid,percent_visits_smoothed_influenza,percent_visits_smoothed_rsv,ed_trends_covid,ed_trends_influenza,ed_trends_rsv,hsa,hsa_counties,hsa_nci_id,fips,trend_source,BuildNumber
0,2022-10-01,Alabama,Bibb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Unavailable,Data Unavailable,Data Unavailable,"Jefferson (Birmingham), AL - Shelby, AL","Bibb, Blount, Chilton, Cullman, Jefferson, She...",150,1007,HSA,2026-01-16
1,2022-10-01,Alabama,Calhoun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Unavailable,Data Unavailable,Data Unavailable,"Calhoun (Anniston), AL - Cleburne, AL","Calhoun, Cleburne",177,1015,HSA,2026-01-16
2,2022-10-01,Alabama,Chilton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Unavailable,Data Unavailable,Data Unavailable,"Jefferson (Birmingham), AL - Shelby, AL","Bibb, Blount, Chilton, Cullman, Jefferson, She...",150,1021,HSA,2026-01-16
3,2022-10-01,Alabama,Cleburne,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Unavailable,Data Unavailable,Data Unavailable,"Calhoun (Anniston), AL - Cleburne, AL","Calhoun, Cleburne",177,1029,HSA,2026-01-16
4,2022-10-01,Alabama,Coosa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Unavailable,Data Unavailable,Data Unavailable,"Talladega, AL - Clay, AL","Clay, Coosa, Talladega",241,1037,HSA,2026-01-16

In [8]:
mi = nhsn[nhsn['geography'] == 'Michigan'].copy()
mi.head()

,week_end,geography,county,percent_visits_combined,percent_visits_covid,percent_visits_influenza,percent_visits_rsv,percent_visits_smoothed_combined,percent_visits_smoothed_covid,percent_visits_smoothed_influenza,percent_visits_smoothed_rsv,ed_trends_covid,ed_trends_influenza,ed_trends_rsv,hsa,hsa_counties,hsa_nci_id,fips,trend_source,BuildNumber
310,2022-10-01,Michigan,Alcona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Unavailable,Data Unavailable,Data Unavailable,"Alpena, MI - Presque Isle, MI","Alcona, Alpena, Montmorency, Presque Isle",371,26001,HSA,2026-01-16
311,2022-10-01,Michigan,Antrim,1.80,1.60,0.07,0.13,3.01,3.08,0.02,0.10,No Change,No Change,Increasing,"Grand Traverse, MI - Manistee, MI","Antrim, Benzie, Grand Traverse, Kalkaska, Leel...",271,26009,HSA,2026-01-16
312,2022-10-01,Michigan,Benzie,1.80,1.60,0.07,0.13,3.01,3.08,0.02,0.10,No Change,No Change,Increasing,"Grand Traverse, MI - Manistee, MI","Antrim, Benzie, Grand Traverse, Kalkaska, Leel...",271,26019,HSA,2026-01-16
313,2022-10-01,Michigan,Branch,3.29,3.10,0.00,0.23,4.14,3.94,0.01,0.32,No Change,No Change,Increasing,"Jackson (Jackson), MI - Lenawee, MI","Branch, Hillsdale, Jackson, Lenawee",375,26023,HSA,2026-01-16
314,2022-10-01,Michigan,Cheboygan,1.49,1.17,0.32,0.00,1.61,1.60,0.08,0.02,Increasing,No Change,Increasing,"Chippewa, MI - Emmet, MI","Charlevoix, Cheboygan, Chippewa, Emmet, Mackinac",294,26031,HSA,2026-01-16

In [11]:
mi['week_end'] = pd.to_datetime(mi['week_end'])

mi_state = (
    mi.groupby('week_end', as_index=False)
      .agg({
          'percent_visits_smoothed_combined': 'mean',
          'percent_visits_smoothed_influenza': 'mean',
          'percent_visits_smoothed_covid': 'mean'
      })
      .sort_values('week_end')
)

mi_state.head()

,week_end,percent_visits_smoothed_combined,percent_visits_smoothed_influenza,percent_visits_smoothed_covid
0,2022-10-01,3.211646,0.061013,3.089494
1,2022-10-08,3.204557,0.076835,2.960127
2,2022-10-15,3.409367,0.099114,2.892025
3,2022-10-22,3.787468,0.131519,2.843671
4,2022-10-29,4.207342,0.182658,2.760380

In [12]:
mi_state.describe()

,percent_visits_smoothed_combined,percent_visits_smoothed_influenza,percent_visits_smoothed_covid
count,105.000000,172.000000,172.000000
mean,3.051148,1.259985,1.322610
std,2.739731,2.148190,0.989288
min,0.373671,0.022278,0.153291
25%,1.093797,0.065063,0.449652
50%,2.171392,0.144810,1.082785
75%,4.422785,1.542057,1.907975
max,12.759367,9.374810,4.682152

In [13]:
mi_state.shape

(172, 4)

In [14]:
mi_state_2023 = mi_state[mi_state['week_end'] >= '2023-01-01'].copy()
mi_state_2023.shape

(158, 4)

In [17]:
mi_state_2023.head()

,week_end,percent_visits_smoothed_combined,percent_visits_smoothed_influenza,percent_visits_smoothed_covid
14,2023-01-07,8.239747,4.999367,2.524557
15,2023-01-14,5.375316,2.614177,2.091392
16,2023-01-21,3.459494,1.401646,1.771266
17,2023-01-28,2.506456,0.902278,1.623291
18,2023-02-04,2.217975,0.688101,1.617215

In [18]:
mi_state_2023 = mi_state_2023[
    mi_state_2023['week_end'] <= '2024-10-05'
].copy()

mi_state_2023.shape

(92, 4)

In [20]:
mi_state_2023.to_csv(
    'data_curated/nssp_ed_demand_weekly_mi_curated.csv',
    index=False
)

In [24]:
mi_state_2023

,week_end,percent_visits_smoothed_combined,percent_visits_smoothed_influenza,percent_visits_smoothed_covid
14,2023-01-07,8.239747,4.999367,2.524557
15,2023-01-14,5.375316,2.614177,2.091392
16,2023-01-21,3.459494,1.401646,1.771266
17,2023-01-28,2.506456,0.902278,1.623291
18,2023-02-04,2.217975,0.688101,1.617215
...,...,...,...,...
101,2024-09-07,2.417975,0.066962,2.330633
102,2024-09-14,2.264051,0.069114,2.174177
103,2024-09-21,1.985063,0.071139,1.878608
104,2024-09-28,1.695823,0.072278,1.562911
105,2024-10-05,NaN,0.071519,1.299241

In [25]:
mi_state_2023 = mi_state_2023[
    mi_state_2023['week_end'] <= '2024-04-27'
].copy()

In [26]:
mi_state_2023.to_csv(
    'data_curated/nssp_ed_demand_weekly_michigan_curated.csv',
    index=False
)